site_name: submit.vtbs.moe 保姆级食用手册
repo_url: https://github.com/dd-center/vdb
repo_name: "vdb: Vtuber Database"

theme:
  name: material
  logo: https://submit.vtbs.moe/favicon.ico
  favicon: https://submit.vtbs.moe/favicon.ico
  language: zh
  features:
    # - announce.dismiss
    # - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/git-alt

nav:
  - 首页: index.md
  - VTB添加指北:
      - 收录与删除标准: wiki/criterion.md
      - 准备工作: wiki/prepare.md
      - 查重: wiki/duplicate.md
      - 创建并提交vtb: wiki/create.md
      - 创建并提交社团: wiki/create-group.md
  - 我的提交怎么样了？:
      - 查询我的请求状态: status/status.md
  - 收录标准:
      - VTB收录标准: criterion/add-person.md
      - VTB删除标准: criterion/delete-person.md
      - 社团收录标准: criterion/add-group.md
      - 社团删除标准: criterion/delete-group.md

extra:
  social:
    - icon: octicons/mark-github-16
      link: https://github.com/dd-center
      name: GitHub 组织 @DD Center
    - icon: octicons/mark-github-16
      link: https://github.com/dd-center/vdb
      name: GitHub 仓库 Vtuber Database
    - icon: octicons/mark-github-16
      link: https://github.com/dd-center/vtbs.moe
      name: GitHub 仓库 vtbs.moe

plugins:
  - search
  - tags

markdown_extensions:
  - admonition
  - footnotes
